import type { Service } from "./store"

export const categories = [
  { id: "cleaning", name: "Cleaning", icon: "sparkles", color: "#007BFF" },
  { id: "plumbing", name: "Plumbing", icon: "build", color: "#46A3FF" },
  { id: "electrical", name: "Electrical", icon: "flash", color: "#FFB800" },
  { id: "painting", name: "Painting", icon: "brush", color: "#FF6B6B" },
  { id: "carpentry", name: "Carpentry", icon: "hammer", color: "#8B4513" },
  { id: "appliance", name: "Appliance", icon: "settings", color: "#6B7280" },
  { id: "pest", name: "Pest Control", icon: "bug", color: "#10B981" },
  { id: "salon", name: "Salon at Home", icon: "cut", color: "#EC4899" },
]

export const services: Service[] = [
  // Cleaning Services
  {
    id: "clean-1",
    name: "Deep Home Cleaning",
    description:
      "Complete deep cleaning of your home including all rooms, bathrooms, and kitchen. Our experts use eco-friendly products.",
    price: 1499,
    originalPrice: 1999,
    duration: "3-4 hours",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
    rating: 4.8,
    reviews: 2453,
    category: "cleaning",
  },
  {
    id: "clean-2",
    name: "Bathroom Cleaning",
    description: "Thorough bathroom cleaning including tiles, fixtures, and sanitization.",
    price: 499,
    originalPrice: 699,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400",
    rating: 4.7,
    reviews: 1876,
    category: "cleaning",
  },
  {
    id: "clean-3",
    name: "Kitchen Cleaning",
    description: "Deep cleaning of kitchen including chimney, cabinets, and appliances.",
    price: 799,
    originalPrice: 999,
    duration: "2-3 hours",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
    rating: 4.9,
    reviews: 3241,
    category: "cleaning",
  },
  {
    id: "clean-4",
    name: "Sofa Cleaning",
    description: "Professional sofa and upholstery cleaning with stain removal.",
    price: 599,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    rating: 4.6,
    reviews: 987,
    category: "cleaning",
  },
  // Plumbing Services
  {
    id: "plumb-1",
    name: "Tap & Mixer Repair",
    description: "Expert repair and replacement of taps and mixers.",
    price: 199,
    duration: "30-60 mins",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400",
    rating: 4.5,
    reviews: 1234,
    category: "plumbing",
  },
  {
    id: "plumb-2",
    name: "Drain Cleaning",
    description: "Professional drain cleaning and blockage removal.",
    price: 349,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400",
    rating: 4.4,
    reviews: 876,
    category: "plumbing",
  },
  {
    id: "plumb-3",
    name: "Water Tank Cleaning",
    description: "Complete water tank cleaning and sanitization service.",
    price: 899,
    originalPrice: 1199,
    duration: "2-3 hours",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400",
    rating: 4.7,
    reviews: 654,
    category: "plumbing",
  },
  // Electrical Services
  {
    id: "elec-1",
    name: "Fan Installation",
    description: "Professional ceiling fan installation and repair.",
    price: 249,
    duration: "30-45 mins",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400",
    rating: 4.6,
    reviews: 1567,
    category: "electrical",
  },
  {
    id: "elec-2",
    name: "Wiring & Cabling",
    description: "Complete electrical wiring and cabling solutions.",
    price: 499,
    duration: "1-3 hours",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400",
    rating: 4.8,
    reviews: 2134,
    category: "electrical",
  },
  {
    id: "elec-3",
    name: "Switchboard Repair",
    description: "Switchboard repair, replacement and installation.",
    price: 299,
    duration: "30-60 mins",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    rating: 4.5,
    reviews: 987,
    category: "electrical",
  },
  // Painting Services
  {
    id: "paint-1",
    name: "Full Home Painting",
    description: "Complete home painting with premium quality paints.",
    price: 8999,
    originalPrice: 12999,
    duration: "3-5 days",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400",
    rating: 4.9,
    reviews: 876,
    category: "painting",
  },
  {
    id: "paint-2",
    name: "Single Room Painting",
    description: "Professional painting for a single room.",
    price: 2499,
    duration: "1-2 days",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400",
    rating: 4.7,
    reviews: 1234,
    category: "painting",
  },
  // Appliance Services
  {
    id: "app-1",
    name: "AC Service & Repair",
    description: "Complete AC servicing including gas refill and cleaning.",
    price: 449,
    originalPrice: 599,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400",
    rating: 4.6,
    reviews: 3456,
    category: "appliance",
  },
  {
    id: "app-2",
    name: "Washing Machine Repair",
    description: "Expert washing machine repair and servicing.",
    price: 349,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400",
    rating: 4.5,
    reviews: 2134,
    category: "appliance",
  },
  {
    id: "app-3",
    name: "Refrigerator Repair",
    description: "Professional refrigerator repair and gas refilling.",
    price: 399,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400",
    rating: 4.7,
    reviews: 1876,
    category: "appliance",
  },
  // Salon Services
  {
    id: "salon-1",
    name: "Haircut for Women",
    description: "Professional haircut at your home by expert stylists.",
    price: 399,
    duration: "30-45 mins",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400",
    rating: 4.8,
    reviews: 4567,
    category: "salon",
  },
  {
    id: "salon-2",
    name: "Facial & Cleanup",
    description: "Relaxing facial and cleanup with premium products.",
    price: 599,
    originalPrice: 799,
    duration: "45-60 mins",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
    rating: 4.9,
    reviews: 3245,
    category: "salon",
  },
  {
    id: "salon-3",
    name: "Manicure & Pedicure",
    description: "Complete manicure and pedicure service at home.",
    price: 699,
    duration: "1-1.5 hours",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400",
    rating: 4.7,
    reviews: 2876,
    category: "salon",
  },
  // Pest Control
  {
    id: "pest-1",
    name: "General Pest Control",
    description: "Complete pest control for cockroaches, ants, and spiders.",
    price: 999,
    originalPrice: 1499,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1632935190605-908275c54cf0?w=400",
    rating: 4.6,
    reviews: 1567,
    category: "pest",
  },
  {
    id: "pest-2",
    name: "Termite Control",
    description: "Advanced termite control treatment for your home.",
    price: 2999,
    duration: "3-4 hours",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    rating: 4.8,
    reviews: 876,
    category: "pest",
  },
  // Carpentry
  {
    id: "carp-1",
    name: "Furniture Assembly",
    description: "Professional furniture assembly and installation.",
    price: 299,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    rating: 4.5,
    reviews: 1234,
    category: "carpentry",
  },
  {
    id: "carp-2",
    name: "Door Repair",
    description: "Door repair, alignment, and lock installation.",
    price: 349,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    rating: 4.6,
    reviews: 987,
    category: "carpentry",
  },
]

export const getServicesByCategory = (categoryId: string) => {
  return services.filter((service) => service.category === categoryId)
}

export const getServiceById = (id: string) => {
  return services.find((service) => service.id === id)
}

export const getFeaturedServices = () => {
  return services.filter((service) => service.originalPrice).slice(0, 6)
}

export const getPopularServices = () => {
  return [...services].sort((a, b) => b.reviews - a.reviews).slice(0, 6)
}
